name: keepershield_rpg
description: "KeeperShield RPG, your ultimate digital ally for mastering epic adventures in Role-Playing Game!"
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  cupertino_icons: any
  provider: any
  intl: any
  objectbox_flutter_libs: any
  objectbox: any

dev_dependencies:
  objectbox_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/img/
